//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerSet
    {
        public AnswerSet()
        {
            this.UserAnswerSets = new HashSet<UserAnswerSet>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public bool IsRight { get; set; }
        public int QuestionId { get; set; }
    
        public virtual QuestionSet QuestionSet { get; set; }
        public virtual ICollection<UserAnswerSet> UserAnswerSets { get; set; }
    }
}
