//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileQuiz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileQuizEntities : DbContext
    {
        public MobileQuizEntities()
            : base("name=MobileQuizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnswerSet> AnswerSets { get; set; }
        public DbSet<QuestionSet> QuestionSets { get; set; }
        public DbSet<QuizSet> QuizSets { get; set; }
        public DbSet<TestSet> TestSets { get; set; }
        public DbSet<UserAnswerSet> UserAnswerSets { get; set; }
        public DbSet<UserSet> UserSets { get; set; }
    }
}
