//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSet
    {
        public QuestionSet()
        {
            this.AnswerSets = new HashSet<AnswerSet>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public int QuizId { get; set; }
    
        public virtual ICollection<AnswerSet> AnswerSets { get; set; }
        public virtual QuizSet QuizSet { get; set; }
    }
}
