//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizSet
    {
        public QuizSet()
        {
            this.QuestionSets = new HashSet<QuestionSet>();
            this.TestSets = new HashSet<TestSet>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<QuestionSet> QuestionSets { get; set; }
        public virtual ICollection<TestSet> TestSets { get; set; }
    }
}
