//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSet
    {
        public TestSet()
        {
            this.UserAnswerSets = new HashSet<UserAnswerSet>();
        }
    
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Quiz_Id { get; set; }
    
        public virtual QuizSet QuizSet { get; set; }
        public virtual UserSet UserSet { get; set; }
        public virtual ICollection<UserAnswerSet> UserAnswerSets { get; set; }
    }
}
