//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswerSet
    {
        public int Id { get; set; }
        public int Answer_Id { get; set; }
        public int Test_Id { get; set; }
    
        public virtual AnswerSet AnswerSet { get; set; }
        public virtual TestSet TestSet { get; set; }
    }
}
